"""add due_date to achievements

Revision ID: 58ce9f183370
Revises: 0b501f407052
Create Date: 2026-02-25 16:02:49.572610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58ce9f183370'
down_revision: Union[str, Sequence[str], None] = '0b501f407052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'due_date')
    # ### end Alembic commands ###
