"""add users table

Revision ID: 96312e3b46ae
Revises: 58ce9f183370
Create Date: 2026-07-24 16:14:56.584833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96312e3b46ae'
down_revision: Union[str, Sequence[str], None] = '58ce9f183370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('achievements', sa.Column('user_id', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('achievements', 'current_value',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'achievements', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.alter_column('achievements', 'current_value',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('achievements', 'user_id')
    op.drop_column('achievements', 'created_at')
    # ### end Alembic commands ###
